title: "seattle.io"
description: "learn about seattle."
url: 'http://localhost:4000'
baseurl: ''

permalink: pretty
google_analytics_id: UA-xxx-x
server: true
auto: true
exclude:
- .gitignore
- README.md