title: "seattle.io"
description: "Books about Seattle, WA. Book #1: local indie video game developers. Learn about Seattle!"
url: 'http://seattle.io'
baseurl: ''
markdown: redcarpet
permalink: pretty
google_analytics_id: UA-43023400-1
exclude:
- .gitignore
- README.md